<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Reviews.Domain\MoviePlatform.Modules.Reviews.Domain.csproj" />
    <ProjectReference Include="..\Reviews.Application\MoviePlatform.Modules.Reviews.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Infrastructure\MoviePlatform.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
